if not exists(
    select *
    from sys.schemas s
    where s.name = 'acu'
)
begin
    exec('create schema acu');
end
if not exists(
    select * 
    from sys.tables t 
    inner join sys.schemas s on t.schema_id = s.schema_id
    where t.name = 'ARTran' and s.name = 'acu'
)
begin
    create table acu.ARTran(
    TranType char(3) not null,
    Type varchar(11),
    RefNbr varchar(15) not null,
    LineNbr int not null,
    SortOrder int,
    AcctID int,
    AcctCD varchar(10),
    SubID int,
    AccrueCost bit,
    CostBasis char(1),
    TranAmt decimal(18,2),
    CashDiscBal decimal(18,2),
    OrigRetainageAmt decimal(18,2),
    RetainageBal decimal(18,2),
    OrigTranAmt decimal(18,2),
    TranBal decimal(18,2),
    TaxableAmt decimal(18,2),
    TaxAmt decimal(18,2),
    OrigTaxableAmt decimal(18,2),
    OrigTaxAmt decimal(18,2),
    RetainedTaxableAmt decimal(18,2),
    RetainedTaxAmt decimal(18,2),
    Qty int,
    BaseQty int,
    AccruedCost decimal(18,2),
    TranCost decimal(18,2),
    TranCostOrig decimal(18,2),
    IsTranCostFinal bit,
    ExtPrice decimal(18,2),
    LineAmt decimal(18,2),
    DiscountsAppliedToLine varchar(10),
    OrigLineNbr int,
    OrigGroupDiscountRate decimal(18,2),
    OrigDocumentDiscountRate decimal(18,2),
    GroupDiscountRate decimal(18,2),
    DocumentDiscountRate decimal(18,2),
    TranClass char(1),
    DrCr char(1),
    TranDate date,
    OrigInvoiceDate date,
    TranDesc varchar(256),
    Released bit not null,
    InventoryID int,
    SiteID int,
    ReasonCode varchar(20),
    LineType char(2),
    TaxCategoryID varchar(15),
    AvalaraCustomerUsageType char(1),
    UnitPrice decimal(18,2),
    SalesPersonID int,
    SalespersonCD varchar(15),
    EmployeeID int,
    CommnPct decimal(18,2),
    CommnAmt decimal(18,2),
    Commissionable bit,
    FinPeriodID char(6),
    TranPeriodID char(6),
    CustomerID varchar(30),
    SOOrderType char(2),
    SOOrderNbr varchar(15),
    SOOrderLineNbr int,
    SOOrderLineOperation char(1),
    SOOrderSortOrder int,
    SOShipmentType char(1),
    SOShipmentNbr varchar(15),
    SOShipmentLineNbr int,
    DiscountID varchar(10),
    DiscountSequenceID varchar(10),
    DiscPct decimal(18,2),
    DiscAmt decimal(18,2),
    ManualPrice bit,
    AutomaticDiscountsDisabled bit,
    ManualDisc bit,
    DisableAutomaticTaxCalculation bit,
    SkipLineDiscounts bit,
    OrigDocType char(3),
    OrigRefNbr varchar(15),
    LocationID int,
    OrigInvoiceType char(3),
    OrigInvoiceNbr varchar(15),
    OrigInvoiceLineNbr int,
    InvtDocType char(1),
    InvtRefNbr varchar(15),
    IsStockItem bit,
    IsCancellation bit,
    Canceled bit,
    SubstitutionRequired bit,
    SOOrderLineSign smallint,
    InvtReleased bit,
    SOShipmentLineGroupNbr int,
    Created_Username varchar(355),
    Created_Name varchar(255),
    Created_ScreenID char(8),
    Created_Datetime datetime,
    LastMod_Username varchar(355),
    LastMod_Name varchar(255),
    LastMod_ScreenID char(8),
    LastMod_Datetime datetime,
    NoteID uniqueidentifier,
    InsertedDT datetime,
    LastChecked datetime,
    primary key(TranType, RefNbr, LineNbr))
end