
if not exists(
    select *
    from sys.schemas s
    where s.name = 'klaviyo'
)
begin
    exec('create schema klaviyo');
end
if not exists(
    select * 
    from sys.tables t 
    inner join sys.schemas s on t.schema_id = s.schema_id
    where t.name = 'ProfileProperties' and s.name = 'klaviyo'
)
begin
create table klaviyo.ProfileProperties(
ID varchar(32) not null primary key,
AcceptsMarketing bit,
ShopifyTags varchar(155),
DateCreated datetime,
LastMailedDate datetime,
LastOpenedDate datetime,
Consent varchar(15),
ConsentTimestamp datetime,
Source varchar(25),
PhoneNumberRegion varchar(5),
HubspotRecordID varchar(25),
LeadStatusPhone varchar(25),
ContactOwnerPhone varchar(95),
Timestamp datetime,
CreativeID varchar(10),
SMSAttentiveSignup varchar(25),
SMSConsentMethod int,
ConsentMethod varchar(35),
ConsentFormID varchar(10),
ConsentFormVersion varchar(35),
ExpectedDateOfNextOrder date,
UTMSource varchar(35),
UTMMedium varchar(35),
UTMCampaign varchar(255),
UTMContent varchar(255),
UTMTerm varchar(35),
ShoppingFor varchar(255),
MobilityIssues varchar(15),
Features varchar(355),
Brand varchar(25),
VeteranStatus varchar(25),
Birthday date,
Clicks int,
Opens int,
FullName varchar(25),
CustomerID varchar(15),
MothersDayOptOut varchar(15),
NumberOfOrders int,
Latitude decimal(8,6),
Longitude decimal(9,6),
InitialSource varchar(45),
LastSource varchar(45),
StoreInterest varchar(25),
Coupon varchar(15),
OkendoFamilyName varchar(95),
OkendoGivenName varchar(135),
Product varchar(35),
Company varchar(55),
HubspotOriginalSource varchar(95),
HubspotOriginalSourceDrillDown1 varchar(155),
HubspotOriginalSourceDrillDown2 varchar(255),
ProductForYouOrSomeoneElse varchar(55),
PrimaryProductUser varchar(55),
TypeOfFirstEngagement varchar(55),
LeadSource varchar(35),
BreadFinanceOutcome varchar(55),
ShippingState varchar(55),
ShippingZip varchar(55),
TextOptIn varchar(20),
EmailOption varchar(20),
MemberHasAccessedPrivateContent varchar(10),
LegalBasis varchar(155),
OkendoNumberOfSurveyResponses int,
AmazonInterest varchar(10),
LastReferringDomain varchar(45),
InterestedInCategory varchar(15),
HasReceivedDigitalCatalog varchar(10),
AmazonOrStore varchar(25),
FathersDayOptOut varchar(25),
InitialReferringDomain varchar(45),
LastContactedOnPhone varchar(35),
LastEventDate datetime,
OkendoAverageReviewRating decimal(18,4),
OkendoHasSubmittedMedia bit,
OkendoLatestReviewRating int,
OkendoNumberOfReviews int,
OkendoAverageReviewSentiment varchar(25),
OkendoLatestReviewSentiment varchar(25),
UserStatus varchar(35),
AdditionalEmail varchar(55),
CallDisposition varchar(55),
DateOrderPlaced datetime,
RepEmail varchar(25),
Unengaged bit,
OkendoLatestNPSCategory varchar(25),
OkendoLatestNPS int,
OkendoLatestNPSDate datetime,
TypeOfFirstEngagementHubspot varchar(55),
ItemDescription varchar(255),
Undefined varchar(55),
UgcFreeItem varchar(55),
CompanyID varchar(55),
EmailContentPreference varchar(155),
InsertedDT datetime,
LastChecked datetime,
)
end
