import os
from dotenv import load_dotenv

load_dotenv()


TABLES = {
    'rmi_Receipts':{
        'keys': ['RMANumber', 'ReceiptID', 'RMAID', 'RMALineID'],
        'columns': [
            'RMANumber',
            'ReceiptDate',
            'ReceiptID',
            'RMAID',
            'RMALineID',
            'Qty',
            'InventoryCD',
            'Location',
            'ItemType',
            'ItemCategory',
            'Descr',
            'Price',
            'Cost'
        ],
        'update_columns':['ReceiptDate', 'Qty', 'InventoryCD', 'Location', 'ItemType', 'ItemCategory', 'Descr', 'Price', 'Cost']
    },    
    'rmi_ClosedShipments':{
        'keys': ['RMANumber', 'RMAID', 'RMALineID', 'RMAType'],
        'columns': [
            'RMANumber',
            'RMAID',
            'RMALineID',
            'RMAType',
            'CreateDate',
            'ShipDate',
            'InventoryCD',
            'QtyShipped',
            'QtyToShip',
            'Location',
            'ItemCategory',
            'Descr',
            'Carrier',
            'CarrierCode',
            'Priority',
            'Tracking',
            'FreightCost',
            'OutboundShipMethod'
        ],
        'update_columns':[
            'CreateDate',
            'ShipDate',
            'InventoryCD',
            'QtyShipped',
            'QtyToShip',
            'Location',
            'ItemCategory',
            'Descr',
            'Carrier',
            'CarrierCode',
            'Priority',
            'Tracking',
            'FreightCost',
            'OutboundShipMethod'
        ]
    }, 
    'rmi_RMAStatus':{
        'keys': ['RMANumber', 'RMAID', 'RMALineID', 'RMAType'],
        'columns': [
            'RMANumber',
            'RMAID',
            'RMALineID',
            'RMAType',
            'RMAStatus',
            'CustomerRef',
            'RMALineNbr',
            'LineStatus',
            'InventoryCD',
            'Qty',
            'Descr',
            'RMATypeName',
            'CreateDate',
            'RMILastModifiedDate',
            'LastChecked',
            'Carrier',
            'Priority'
        ],
        'update_columns':[
            'RMAStatus',
            'CustomerRef',
            'RMALineNbr',
            'LineStatus',
            'InventoryCD',
            'Qty',
            'Descr',
            'RMATypeName',
            'CreateDate',
            'RMILastModifiedDate',
            'LastChecked',
            'Carrier',
            'Priority'
        ]
    }, 
    'RedstagInventorySummary':{
        'keys': ['InventoryCD',],
        'columns': [
            'InventoryCD',
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ],
        'update_columns':[
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ]
    },
    'RedstagInventoryDetail':{
        'keys': ['InventoryCD', 'Warehouse'],
        'columns': [
            'InventoryCD',
            'Warehouse',
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ],
        'update_columns':[
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ]
    },
    '_util.acu_api_log':{
        'keys': [
            'Entity',
            'KeyValue',
            'Operation',
            'Timestamp'
        ],
        'columns': [
            'Entity',
            'KeyValue',
            'Operation',
            'Payload',
            'Response',
            'Timestamp'
        ],
        'update_columns':[
            'Payload',
            'Response',
        ]
    },
    '_util.SOOrderDeletions':{
        'keys': ['OrderType', 'OrderNbr'],
        'columns': [
            'OrderType',
            'OrderNbr',
            'DeletedBy',
            'DeletedDatetime'
        ],
        'update_columns':[
            'DeletedBy',
            'DeletedDatetime'
        ]
    },
    '_util.SOLineDeletions':{
        'keys': ['OrderType', 'OrderNbr', 'LineNbr'],
        'columns': [
            'OrderType',
            'OrderNbr',
            'LineNbr',
            'OrderDate',
            'DeletedDatetime',
            'DeletedBy',
            'InventoryID',
            'SubItemID',
            'SiteID',
            'LocationID',
            'OrderQty',
            'ShippedQty',
            'UnitPrice',
            'UnitCost',
            'ExtPrice',
            'ExtCost',
            'DiscPct',
            'DiscAmt',
            'ManualDisc',
            'ReasonCode',
            'OpenQty',
            'OpenAmt',
            'LineAmt',
            'Completed',
            'OrigOrderType',
            'OrigOrderNbr',
            'OrigLineNbr',
            'OrigShipmentType',
            'OpenLine',
            'BilledQty',
            'UnbilledQty',
            'UnbilledAmt',
            'ShipDate',
            'CancelDate',
            'BilledAmt',
            'DiscountID',
            'DiscountSequenceID',
            'InvoiceType',
            'InvoiceNbr',
            'InvoiceLineNbr',
            'InvoiceDate',
            'IsFree',
            'POCreate',
            'POCreated',
            'POSource',
            'POSiteID',
            'QtyOnOrders',
            'CustomerOrderNbr',
            'POCreateDate',
            'IsStockItem',
            'NetSales',
            'MarginAmt',
            'MarginPct',
            'CreatedDatetime',
            'CreatedBy',
        ],
        'update_columns':[
            'OrderDate',
            'DeletedDatetime',
            'DeletedBy',
            'InventoryID',
            'SubItemID',
            'SiteID',
            'LocationID',
            'OrderQty',
            'ShippedQty',
            'UnitPrice',
            'UnitCost',
            'ExtPrice',
            'ExtCost',
            'DiscPct',
            'DiscAmt',
            'ManualDisc',
            'ReasonCode',
            'OpenQty',
            'OpenAmt',
            'LineAmt',
            'Completed',
            'OrigOrderType',
            'OrigOrderNbr',
            'OrigLineNbr',
            'OrigShipmentType',
            'OpenLine',
            'BilledQty',
            'UnbilledQty',
            'UnbilledAmt',
            'ShipDate',
            'CancelDate',
            'BilledAmt',
            'DiscountID',
            'DiscountSequenceID',
            'InvoiceType',
            'InvoiceNbr',
            'InvoiceLineNbr',
            'InvoiceDate',
            'IsFree',
            'POCreate',
            'POCreated',
            'POSource',
            'POSiteID',
            'QtyOnOrders',
            'CustomerOrderNbr',
            'POCreateDate',
            'IsStockItem',
            'NetSales',
            'MarginAmt',
            'MarginPct',
            'CreatedDatetime',
            'CreatedBy',
        ]
    },
    '_util.SOShipmentDeletions':{
        'keys': ['ShipmentNbr'],
        'columns': [
            'ShipmentNbr',
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ],
        'update_columns':[
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ]
    },
    '_util.SOOrderShipmentDeletions':{
        'keys': ['OrderType', 'OrderNbr', 'ShipmentNbr'],
        'columns': [
            'OrderType',
            'OrderNbr',
            'ShipmentNbr',
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ],
        'update_columns':[
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ]
    },
    'AdDetails': {
        'keys': [
            'AdCode',
        ],
        'columns': [
            'AdCode',
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
        'update_columns': [
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
    },
    'criteo.campaign_performance_daily': {
        'keys': [
            'report_date',
            'campaign_id'
        ],
        'columns': [
            'report_date',
            'advertiser_id',
            'campaign_id',
            'campaign_name',
            'impressions',
            'clicks',
            'cost',
            'conversions',
            'revenue',
            'load_timestamp',

        ],
        'update_columns': [
            'advertiser_id',
            'campaign_name',
            'impressions',
            'clicks',
            'cost',
            'conversions',
            'revenue',
            'load_timestamp',
        ],
    },
    'criteo.diff_log': {
        'keys': [
            'report_date',
            'campaign_id',
            'last_ts'
        ],
        'columns': [
            'report_date',
            'campaign_id',
            'last_ts',
            'current_ts',
            'impr_current',
            'impr_last',
            'clicks_current',
            'clicks_last',
            'cost_current',
            'cost_last',
            'revenue_current',
            'revenue_last',
            'diff'
        ],
        'update_columns': [
            'current_ts',
            'impr_current',
            'impr_last',
            'clicks_current',
            'clicks_last',
            'cost_current',
            'cost_last',
            'convr_current',
            'convr_last',
            'revenue_current',
            'revenue_last',
            'diff'
        ],
    },
    'acu.Quotes': {
        'keys': [
            'OrderType',
            'QuoteNbr',
            'LineNbr',
        ],
        'columns': [
            'OrderType',
            'QuoteNbr',
            'LineNbr',
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'LastModifiedDT',
            'CreatedDT',
            'AttachedOrderType',
            'AttachedOrderNbr',
            'LastChecked'
        ],
        'update_columns': [
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'LastModifiedDT',
            'CreatedDT',
            'AttachedOrderType',
            'AttachedOrderNbr',
            'LastChecked'
        ],
    },
    'acu.SalesOrders': {
        'keys': [
            'OrderType',
            'OrderNumber',
            'LineNbr',
        ],
        'columns': [
            'OrderType',
            'OrderNumber',
            'LineNbr',
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'LastModifiedDT',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'ShipDate',
            'ShipmentNbr',
            'ShipStatus',
            'ShipmentWH',
            'Completed',
            'OriginalOrderType',
            'OriginalOrderNbr',
            'FreightPrice',
            'PremiumFreightPrice',
            'FreightTotal',
            'CreatedDT',
            'CreatedBy',
            'LastModifiedBy',
            'LastChecked',
            'POCreate',
            'POCreated',
            'POCreateDate',
            'POWarehouse',
            'PONbr',
        ],
        'update_columns': [
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'LastModifiedDT',
            'DiscountCode',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'ShipDate',
            'ShipmentNbr',
            'ShipStatus',
            'ShipmentWH',
            'Completed',
            'OriginalOrderType',
            'OriginalOrderNbr',
            'FreightPrice',
            'PremiumFreightPrice',
            'FreightTotal',
            'CreatedDT',
            'CreatedBy',
            'LastModifiedBy',
            'LastChecked',
            'POCreate',
            'POCreated',
            'POCreateDate',
            'POWarehouse',
            'PONbr',
        ],
    },
    #     'json.K_OrderIngest': {
    #     'keys': [
    #         'OrderNbr',
    #         'AcuStatus',
    #     ],
    #     'columns': [
    #         'OrderNbr',
    #         'jsonData',
    #         'AcuStatus',
    #         'DatetimeSent',
    #         'ResponseText',
    #     ],
    #     'update_columns': [
    #         'jsonData',
    #         'DatetimeSent',
    #         'ResponseText',
    #     ],
    # },
    'K_OrderIngest': {
        'keys': [
            'OrderNbr',
            'Status',
        ],
        'columns': [
            'OrderNbr',
            'jsonData',
            'AcuStatus',
            'DatetimeSent',
            'ResponseText',
            'Status',
            'LastChecked',
        ],
        'update_columns': [
            'jsonData',
            'DatetimeSent',
            'ResponseText',
            'LastChecked',
        ],
    },
    'acu.Shipments': {
        'keys': [
            'ShipmentNbr',
            'ShipLineNbr',
            'OrderNbr',
            'OrderLineNbr',
        ],
        'columns': [
            'ShipmentNbr',
            'ShipLineNbr',
            'Status',
            'OrderNbr',
            'OrderLineNbr',
            'OrderDate',
            'InventoryCD',
            'OrderQTY',
            'ShipQTY',
            'ShipDate',
            'CustomerID',
            'AccountName',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Country',
            'Zip',
            'WarehouseID',
            'PackageCount',
            'SOLinePrice',
            'FreightCost',
            'SenttoWH',
            'InsertedDT',
            'LastModifiedDT',
            'Tracking',
            'TrackingCreatedDate',
            'CustomerPhone',
            'Attention',
            'ShipVia',
            'Carrier',
            'CourierCode',
            'CourierName',
            'ConfirmedDateTime',
            'CreatedDatetime',
        ],
        'update_columns': [
            'Status',
            'OrderDate',
            'InventoryCD',
            'OrderQTY',
            'ShipQTY',
            'ShipDate',
            'CustomerID',
            'AccountName',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Country',
            'Zip',
            'WarehouseID',
            'PackageCount',
            'SOLinePrice',
            'FreightCost',
            'SenttoWH',
            'InsertedDT',
            'LastModifiedDT',
            'Tracking',
            'TrackingCreatedDate',
            'CustomerPhone',
            'Attention',
            'ShipVia',
            'Carrier',
            'CourierCode',
            'CourierName',
            'ConfirmedDateTime',
            'CreatedDatetime',
        ],
    },
    '_util.AfterShipLog': {
        'keys': [
            'ShipmentNbr',
            'OrderNbr',
            'Tracking',
        ],
        'columns': [
            'ShipmentNbr',
            'OrderNbr',
            'Tracking',
            'ResponseCode',
            'Message',
            'ID',
            'Timestamp'
        ],
        'update_columns': [
            'ResponseCode',
            'Message',
            'ID',
            'Timestamp'
        ],
    },
    'hs.deal_snapshots': {
        'keys': [
            'snapshot_at',
            'deal_id',
            'stage',
            'rep_name',
        ],
        'columns': [
            'snapshot_at',
            'deal_id',
            'deal_name',
            'stage',
            'deal_type',
            'rep_name',
            'team',
            'product',
            'amount',
            'lead_source',
            'order_number',
            'is_true_won',
            'is_stalled',
            'create_date',
            'close_date',
            'last_activity_date',
            'days_in_pipeline',
            'days_since_activity',
            'closed_lost_reason',
            'primary_competitor',
        ],
        'update_columns': [
            'deal_name',
            'deal_type',
            'team',
            'product',
            'amount',
            'lead_source',
            'order_number',
            'is_true_won',
            'is_stalled',
            'create_date',
            'close_date',
            'last_activity_date',
            'days_in_pipeline',
            'days_since_activity',
            'closed_lost_reason',
            'primary_competitor',
        ],
    },
    'hs.deal_tracking': {
        'keys': [
            'deal_id',
            'stage',
            'rep_name',
        ],
        'columns': [
            'deal_id',
            'deal_name',
            'stage',
            'deal_type',
            'rep_name',
            'team',
            'product',
            'amount',
            'lead_source',
            'order_number',
            'is_true_won',
            'is_stalled',
            'create_date',
            'close_date',
            'last_activity_date',
            'days_in_pipeline',
            'days_since_activity',
            'closed_lost_reason',
            'primary_competitor',
            'snapshot_at',
        ],
        'update_columns': [
            'deal_name',
            'deal_type',
            'team',
            'product',
            'amount',
            'lead_source',
            'order_number',
            'is_true_won',
            'is_stalled',
            'create_date',
            'close_date',
            'last_activity_date',
            'days_in_pipeline',
            'days_since_activity',
            'closed_lost_reason',
            'primary_competitor',
            'snapshot_at',
        ],
    },
    'hs.activity_snapshots': {
        'keys': [
            'rep_name',
            'window',
            'window_start',
            'window_end'
        ],
        'columns': [
            'rep_name',
            'team',
            'window',
            'call_count',
            'email_count',
            'meeting_count',
            'task_count',
            'new_contact_count',
            'window_start',
            'window_end',
            'snapshot_at',
        ],
        'update_columns': [
            'call_count',
            'email_count',
            'meeting_count',
            'task_count',
            'new_contact_count',
            'team',
            'snapshot_at',
        ],
    },
    'SOShipmentKvExt': {
        'keys': [
            'CompanyID',
            'RecordID',
            'FieldName',
        ],
        'columns': [
            'CompanyID',
            'RecordID',
            'FieldName',
            'ValueNumeric',
            'ValueDate',
            'ValueString',
            'ValueText',
        ],
        'update_columns': [
            'ValueNumeric',
            'ValueDate',
            'ValueString',
            'ValueText',
        ],
    },
    'acu.AftershipExportv2': {
        'keys': [
            'OrderNbr',
            'Tracking',
        ],
        'columns': [
            'OrderNbr',
            'Tracking',
            'Phone',
            'Product',
            'ShipmentType',
            'ShipmentWeight',
            'Link',
            'DestLine1',
            'DestCity',
            'DestState',
            'DestZip',
            'Tag',
            'Subtag',
            'SubtagMessage',
            'CreatedTime',
            'LastUpdateTime',
            'ID',
            'ShipmentNbr',
        ],
        'update_columns': [
            'Phone',
            'Product',
            'ShipmentType',
            'ShipmentWeight',
            'Link',
            'DestLine1',
            'DestCity',
            'DestState',
            'DestZip',
            'Tag',
            'Subtag',
            'SubtagMessage',
            'CreatedTime',
            'LastUpdateTime',
            'ID',
            'ShipmentNbr',
        ],
    },
    'acu.AftershipExportDetailv2': {
        'keys': [
            'OrderNbr',
            'Tracking',
            'CheckpointTime',
            'CheckpointCreatedTime',
        ],
        'columns': [
            'OrderNbr',
            'Tracking',
            'CheckpointTime',
            'CheckpointCreatedTime',
            'Message',
            'Tag',
            'Subtag',
            'SubtagMessage',
            'City',
            'State',
            'Zip',
            'Slug',
            'RawTag',
            'Source',
            'ID',
            'ShipmentNbr',
        ],
        'update_columns': [
            'Message',
            'Tag',
            'Subtag',
            'SubtagMessage',
            'City',
            'State',
            'Zip',
            'Slug',
            'RawTag',
            'Source',
            'ID',
            'ShipmentNbr',
        ],
    },
    'hs.Properties': {
        'keys': [
            'ObjectType',
            'Name',
        ],
        'columns': [
            'ObjectType',
            'Name',
            'Label',
            'GroupName',
            'Description',
            'Type',
            'FieldType',
            'CreatedUserId',
            'UpdatedUserId',
            'DisplayOrder',
            'Calculated',
            'Archived',
            'Hidden',
            'HubspotDefined',
            'CreatedAt',
            'UpdatedAt',
        ],
        'update_columns': [
            'Label',
            'GroupName',
            'Description',
            'Type',
            'FieldType',
            'CreatedUserId',
            'UpdatedUserId',
            'DisplayOrder',
            'Calculated',
            'Archived',
            'Hidden',
            'HubspotDefined',
            'CreatedAt',
            'UpdatedAt',
        ],
    },
    'acu.PhoneRevByMonth': {
        'keys': [
            'AcctCD',
            'OrderNbr',
            'LineNbr',
        ],
        'columns': [
            'AcctCD',
            'Name',
            'Phone',
            'OrderNbr',
            'LineNbr',
            'OrderDate',
            'OrderStatus',
            'InventoryCD',
            'Descr',
            'LineAmt',
            'Agent',
        ],
        'update_columns': [
            'Name',
            'Phone',
            'OrderDate',
            'OrderStatus',
            'InventoryCD',
            'Descr',
            'LineAmt',
            'Agent',
        ],
    },
    'acu.Shipments': {
        'keys': [
            'ShipmentNbr',
            'ShipLineNbr',
            'OrderNbr',
            'OrderLineNbr',
        ],
        'columns': [
            'ShipmentNbr',
            'ShipLineNbr',
            'Status',
            'OrderNbr',
            'OrderLineNbr',
            'OrderDate',
            'InventoryCD',
            'OrderQTY',
            'ShipQTY',
            'ShipDate',
            'CustomerID',
            'AccountName',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Country',
            'Zip',
            'WarehouseID',
            'PackageCount',
            'SOLinePrice',
            'FreightCost',
            'SenttoWH',
            'InsertedDT',
            'LastModifiedDT',
            'Tracking',
            'TrackingCreatedDate',
            'CustomerPhone',
            'Attention',
            'ShipVia',
            'Carrier',
            'CourierCode',
            'CourierName',
            'ConfirmedDatetime',
            'CreatedDatetime',
            'SentToWHDatetime',
            'PackageDescr',
            'CreatedBy',
            'LastModifiedBy',
            'LastChecked',
        ],
        'update_columns': [
            'Status',
            'OrderDate',
            'InventoryCD',
            'OrderQTY',
            'ShipQTY',
            'ShipDate',
            'CustomerID',
            'AccountName',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Country',
            'Zip',
            'WarehouseID',
            'PackageCount',
            'SOLinePrice',
            'FreightCost',
            'SenttoWH',
            'LastModifiedDT',
            'Tracking',
            'TrackingCreatedDate',
            'CustomerPhone',
            'Attention',
            'ShipVia',
            'Carrier',
            'CourierCode',
            'CourierName',
            'ConfirmedDatetime',
            'CreatedDatetime',
            'SentToWHDatetime',
            'PackageDescr',
            'CreatedBy',
            'LastModifiedBy',
            'LastChecked',
        ],
    },
    'acu.Customers': {
        'keys': [
            'CustomerID',
        ],
        'columns': [
            'CustomerID',
            'CustomerClass',
            'ContactName',
            'AccountName',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'Phone',
            'Email',
            'Terms',
            'AccountID',
            'ContactID',
            'CUSTEDP',
            'SalesPersonID',
            'SalesPersonName',
            'CreatedOn',
            'CreatedBy',
            'InsertedDT',
            'LastModifiedDT',
            'Phone2',
            'LastChecked',
        ],
        'update_columns': [
            'CustomerClass',
            'ContactName',
            'AccountName',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'Phone',
            'Email',
            'Terms',
            'AccountID',
            'ContactID',
            'CUSTEDP',
            'SalesPersonID',
            'SalesPersonName',
            'CreatedOn',
            'CreatedBy',
            'LastModifiedDT',
            'Phone2',
            'LastChecked',
        ],
    },
    'hs.AcuCompanies': {
        'keys': [
            'hsID',
        ],
        'columns': [
            'hsID',
            'hsName',
            'hsCompanyPhone',
            'hsCompanyEmail',
            'hsContacts',
            'hsPhones',
            'hsEmails',
            'acuCustomerIDs',
            'acuCustomers',
            'phone_match',
            'email_match',
            'LastExtracted',
            'LastUpdated',
        ],
        'update_columns': [
            'hsName',
            'hsCompanyPhone',
            'hsCompanyEmail',
            'hsContacts',
            'hsPhones',
            'hsEmails',
            'acuCustomerIDs',
            'acuCustomers',
            'phone_match',
            'email_match',
            'LastExtracted',
            'LastUpdated',
        ],
    },
    'hs.UnmatchedCompanies': {
        'keys': [
            'hsID',
        ],
        'columns': [
            'hsID',
            'hsName',
            'hsCompanyPhone',
            'hsCompanyEmail',
            'hsContacts',
            'hsPhones',
            'hsEmails',
            'LastExtracted',
        ],
        'update_columns': [
            'hsName',
            'hsCompanyPhone',
            'hsCompanyEmail',
            'hsContacts',
            'hsPhones',
            'hsEmails',
            'LastExtracted',
        ],
    },
    'Five9CallSegments': {
        'keys': [
            'CallID',
            'Timestamp',
            'SessionID',
        ],
        'columns': [
            'CallID',
            'Timestamp',
            'CallType',
            'SessionID',
            'CallSegmentID',
            'CalledParty',
            'CallingParty',
            'SegmentType',
            'Result',
            'AfterCallWorkDuration',
            'TalkDuration',
            'HandleDuration',
            'CallDuration',
            'ANI',
            'Skill',
            'DNIS',
            'AnswerSpeed',
            'RingDuration',
            'IVRDuration',
            'QueueWaitDuration',
            'TotalQueueDuration'
        ],
        'update_columns': [
            'CallType',
            'CallSegmentID',
            'CalledParty',
            'CallingParty',
            'SegmentType',
            'Result',
            'TalkDuration',
            'CallDuration',
            'ANI',
            'Skill',
            'DNIS',
            'AfterCallWorkDuration',
            'HandleDuration',
            'AnswerSpeed',
            'RingDuration',
            'IVRDuration',
            'QueueWaitDuration',
            'TotalQueueDuration',
        ],
    },
    'ucmi.DarwillAddresses': {
        'keys': [
            'ANI',
        ],
        'columns': [
            'CustomerID',
            'HubspotID',
            'ANI',
            'Email',
            'Product',
            'ContactName',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'UnformattedANI',
            'SourceFile',
            'DateAdded',
        ],
        'update_columns': [
            'CustomerID',
            'HubspotID',
            'Email',
            'Product',
            'ContactName',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'UnformattedANI',
            'SourceFile',
            'DateAdded',
        ],
    },
    
    'acu.BackordersPointInTime': {
        'keys': [
            'OrderType',
            'OrderNumber',
            'LineNbr',
            'Timestamp',
            'Date',
        ],
        'columns': [
            'OrderType',
            'OrderNumber',
            'LineNbr',
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'LastModifiedDT',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'ShipDate',
            'ShipmentNbr',
            'ShipStatus',
            'ShipmentWH',
            'Completed',
            'OriginalOrderType',
            'OriginalOrderNbr',
            'FreightPrice',
            'PremiumFreightPrice',
            'FreightTotal',
            'CreatedDT',
            'CreatedBy',
            'LastModifiedBy',
            'POCreate',
            'POCreated',
            'POCreateDate',
            'POWarehouse',
            'PONbr',
            'Timestamp',
            'Date',
        ],
        'update_columns': [
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'LastModifiedDT',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'ShipDate',
            'ShipmentNbr',
            'ShipStatus',
            'ShipmentWH',
            'Completed',
            'OriginalOrderType',
            'OriginalOrderNbr',
            'FreightPrice',
            'PremiumFreightPrice',
            'FreightTotal',
            'CreatedDT',
            'CreatedBy',
            'LastModifiedBy',
            'POCreate',
            'POCreated',
            'POCreateDate',
            'POWarehouse',
            'PONbr',
        ],
    },
    'src_dm_tracker': {
        'keys': ['SpendMonth', 'MailName', 'Campaign', 'TFN'],
        'columns': [
            'SpendMonth',
            'InHomeStartDate',
            'MailName',
            'Campaign',
            'TFN',
            'TotalSpend',
            'ProductGroup',
            'LoadTimestamp',
        ],
        'update_columns': [
            'InHomeStartDate',
            'TotalSpend',
            'ProductGroup',
            'LoadTimestamp',
        ],
    },
    'acu.TrialBalance': {
        'keys': [
            'AccountCD',
            'Type',
            'Sub',
            'FinPeriod',
        ],
        'columns': [
            'AccountCD',
            'Type',
            'Sub',
            'Description',
            'FinPeriod',
            'BeginningBalance',
            'Debit',
            'Credit',
            'EndingBalance',
            'StartDate',
            'EndDate',
            'TypeID',
            'SubCD',
            'FinPeriodID',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Description',
            'BeginningBalance',
            'Debit',
            'Credit',
            'EndingBalance',
            'StartDate',
            'EndDate',
            'TypeID',
            'SubCD',
            'FinPeriodID',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsBySkillMonth': {
        'keys': [
            'RawSkill',
            'SkillProduct',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'RawSkill',
            'SkillProduct',
            'Calls',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsBySkillDate': {
        'keys': [
            'RawSkill',
            'SkillProduct',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'RawSkill',
            'SkillProduct',
            'Calls',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsByAgentMonth': {
        'keys': [
            'Agent',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'Agent',
            'Calls',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsByAgentDate': {
        'keys': [
            'Agent',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'Agent',
            'Calls',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsBySkillAgentMonth': {
        'keys': [
            'RawSkill',
            'SkillProduct',
            'Agent',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'RawSkill',
            'SkillProduct',
            'Agent',
            'Calls',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsBySkillAgentDate': {
        'keys': [
            'RawSkill',
            'SkillProduct',
            'Agent',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'RawSkill',
            'SkillProduct',
            'Agent',
            'Calls',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsByDeptMonth': {
        'keys': [
            'Department',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'Department',
            'Calls',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsByDeptDate': {
        'keys': [
            'Department',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'Department',
            'Calls',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsBySkillDeptMonth': {
        'keys': [
            'RawSkill',
            'SkillProduct',
            'Department',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'RawSkill',
            'SkillProduct',
            'Department',
            'Calls',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsBySkillDeptDate': {
        'keys': [
            'RawSkill',
            'SkillProduct',
            'Department',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'RawSkill',
            'SkillProduct',
            'Department',
            'Calls',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsByDuringBusinessHrMonth': {
        'keys': [
            'DuringBusinessHours',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'DuringBusinessHours',
            'Calls',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_CallsByDuringBusinessHrDate': {
        'keys': [
            'DuringBusinessHours',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
        ],
        'columns': [
            'DuringBusinessHours',
            'Calls',
            'Date',
            'Month',
            'Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.JHL_AgentsByMonth': {
        'keys': [
            'Year',
            'FinPeriod',
            'Month',
        ],
        'columns': [
            'Year',
            'FinPeriod',
            'Month',
            'Agents',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Agents',
            'LastChecked',
        ],
    },
    'analytics.JHL_AgentsByDate': {
        'keys': [
            'Year',
            'FinPeriod',
            'Month',
            'Date',
            'DuringBusinessHours',
        ],
        'columns': [
            'Year',
            'FinPeriod',
            'Month',
            'Date',
            'DuringBusinessHours',
            'Agents',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Agents',
            'LastChecked',
        ],
    },
    'analytics.JHL_AdPhone': {
        'keys': [
            'AdCode',
            'TFN',
            'StartDate',
        ],
        'columns': [
            'AdCode',
            'TFN',
            'StartDate',
            'Priority',
            'MatchingAdCodeDate',
            'EndDate',
            'Category',
            'PrimaryAdName',
            'SecondaryAdName',
            'Product',
            'AdVersionID',
            'PrimaryVersionName',
            'SecondaryVersionName',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Priority',
            'EndDate',
            'MatchingAdCodeDate',
            'Category',
            'PrimaryAdName',
            'SecondaryAdName',
            'Product',
            'AdVersionID',
            'PrimaryVersionName',
            'SecondaryVersionName',
            'LastChecked',
        ],
    },
    'analytics.JHL_acuMFRAllocated': {
        'keys': [
            'AdCode',
            'OrderNbr',
            'RowNum',
        ],
        'columns': [
            'AdCode',
            'PrimaryAdName',
            'SecondaryAdName',
            'StartDate',
            'AdVersionID',
            'PrimaryVersionName',
            'SecondaryVersionName',
            'Category',
            'Product',
            'DNIS',
            'Date',
            'AcctCD',
            'Name',
            'CustomerPhone_ANI',
            'OrderDate',
            'OrderNbr',
            'Calls',
            'LineAmtCalc',
            'OrderCount',
            'RowNum',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'PrimaryAdName',
            'SecondaryAdName',
            'StartDate',
            'AdVersionID',
            'PrimaryVersionName',
            'SecondaryVersionName',
            'Category',
            'Product',
            'DNIS',
            'Date',
            'AcctCD',
            'Name',
            'CustomerPhone_ANI',
            'OrderDate',
            'Calls',
            'LineAmtCalc',
            'OrderCount',
            'LastChecked',
        ],
    },
    'analytics.JHL_MFRAllocated': {
        'keys': [
            'RowNum',
            'OrderNbr',
            'AdCode',
        ],
        'columns': [
            'LineAmtCalc',
            'OrderCount',
            'RowNum',
            'MatchRank',
            'DaysBetweenCallOrder',
            'Date',
            'Agent',
            'Department',
            'CalledParty',
            'CustomerPhone_CallingParty',
            'DNIS',
            'CustomerPhone_ANI',
            'TalkDuration',
            'CallDuration',
            'HandleDuration',
            'Year',
            'Month',
            'FinPeriod',
            'SkillProduct',
            'RawSkill',
            'TalkDurationStr',
            'Abandoned',
            'LongerThan90Seconds',
            'DayOfWeek',
            'DuringBusinessHours',
            'TalkSeconds',
            'CallSeconds',
            'HandleSeconds',
            'AfterCallWorkDuration',
            'AfterCallWorkSeconds',
            'TimeStamp',
            'SessionID',
            'DStr',
            'AcctCD',
            'Name',
            'Phone',
            'OrderNbr',
            'LineNbr',
            'OrderDate',
            'OrderStatus',
            'InventoryCD',
            'Descr',
            'LineAmt',
            'LineAmtCalculated',
            'Value',
            'Product',
            'Priority',
            'AdCode',
            'TFN',
            'StartDate',
            'MatchingAdCodeDate',
            'EndDate',
            'PrimaryAdName',
            'Category',
            'AdVersionID',
            'MFRProduct',
            'SecondaryAdName',
            'PrimaryVersionName',
            'SecondaryVersionName',
            'Calls',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'LineAmtCalc',
            'OrderCount',
            'MatchRank',
            'DaysBetweenCallOrder',
            'Date',
            'Agent',
            'Department',
            'CalledParty',
            'CustomerPhone_CallingParty',
            'DNIS',
            'CustomerPhone_ANI',
            'TalkDuration',
            'CallDuration',
            'HandleDuration',
            'Year',
            'Month',
            'FinPeriod',
            'SkillProduct',
            'RawSkill',
            'TalkDurationStr',
            'Abandoned',
            'LongerThan90Seconds',
            'DayOfWeek',
            'DuringBusinessHours',
            'TalkSeconds',
            'CallSeconds',
            'HandleSeconds',
            'AfterCallWorkDuration',
            'AfterCallWorkSeconds',
            'TimeStamp',
            'SessionID',
            'DStr',
            'AcctCD',
            'Name',
            'Phone',
            'LineNbr',
            'OrderDate',
            'OrderStatus',
            'InventoryCD',
            'Descr',
            'LineAmt',
            'LineAmtCalculated',
            'Value',
            'Product',
            'Priority',
            'TFN',
            'StartDate',
            'MatchingAdCodeDate',
            'EndDate',
            'PrimaryAdName',
            'Category',
            'AdVersionID',
            'MFRProduct',
            'SecondaryAdName',
            'PrimaryVersionName',
            'SecondaryVersionName',
            'Calls',
            'LastChecked',
        ],
    },
    'analytics.int_CallCounts': {
        'keys': [
            'TimeStamp',
            'SessionID',
        ],
        'columns': [
            'Date',
            'Agent',
            'Department',
            'CalledParty',
            'CustomerPhone_CallingParty',
            'DNIS',
            'CustomerPhone_ANI',
            'TalkDuration',
            'CallDuration',
            'HandleDuration',
            'Year',
            'Month',
            'FinPeriod',
            'SkillProduct',
            'RawSkill',
            'TalkDurationStr',
            'Abandoned',
            'LongerThan90Seconds',
            'DayOfWeek',
            'DuringBusinessHours',
            'TalkSeconds',
            'CallSeconds',
            'HandleSeconds',
            'AfterCallWorkDuration',
            'AfterCallWorkSeconds',
            'TimeStamp',
            'SessionID',
            'DStr',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Date',
            'Agent',
            'Department',
            'CalledParty',
            'CustomerPhone_CallingParty',
            'DNIS',
            'CustomerPhone_ANI',
            'TalkDuration',
            'CallDuration',
            'HandleDuration',
            'Year',
            'Month',
            'FinPeriod',
            'SkillProduct',
            'RawSkill',
            'TalkDurationStr',
            'Abandoned',
            'LongerThan90Seconds',
            'DayOfWeek',
            'DuringBusinessHours',
            'TalkSeconds',
            'CallSeconds',
            'HandleSeconds',
            'AfterCallWorkDuration',
            'AfterCallWorkSeconds',
            'DStr',
            'LastChecked',
        ],
    },
    'analytics.JHL_SalesSummary': {
        'keys': [
            'MetricBucket',
            'FinPeriod',
            'FinPeriodTotal',
        ],
        'columns': [
            'MetricBucket',
            'FinPeriod',
            'Booked',
            'Shipped',
            'FinPeriodTotal',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Booked',
            'Shipped',
            'InsertedDT',
            'LastChecked',
        ],
    },
    'analytics.int_SalesSummary': {
        'keys': [
            'MetricBucket',
            'DatePlaced',
            'FinPeriod',
            'FinPeriodTotal',
        ],
        'columns': [
            'MetricBucket',
            'DatePlaced',
            'FinPeriod',
            'Booked',
            'Shipped',
            'FinPeriodTotal',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'Booked',
            'Shipped',
            'InsertedDT',
            'LastChecked',
        ],
    },
    'analytics.raw_SalesSummary': {
        'keys': [
            'OrderType',
            'OrderNbr',
            'CustomerID',
            'LineNbr',
        ],
        'columns': [
            'OrderType',
            'OrderNbr',
            'DatePlaced',
            'CustomerID',
            'CustomerClass',
            'InventoryCD',
            'Qty',
            'LinePrice',
            'DiscountAmt',
            'Revenue',
            'Status',
            'CustTypeBucket',
            'Channel',
            'Shipped',
            'Booked',
            'ItemDescr',
            'ItemClassDescr',
            'PostingClass',
            'ItemType',
            'LineCost',
            'Salesperson',
            'LineNbr',
            'Lines',
            'CustomerName',
            'ShipmentNbr',
            'Total_WarrantyRevenue',
            'Date_Month',
            'Date_Year',
            'FinPeriod',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'DatePlaced',
            'CustomerClass',
            'InventoryCD',
            'Qty',
            'LinePrice',
            'DiscountAmt',
            'Revenue',
            'Status',
            'CustTypeBucket',
            'Channel',
            'Shipped',
            'Booked',
            'ItemDescr',
            'ItemClassDescr',
            'PostingClass',
            'ItemType',
            'LineCost',
            'Salesperson',
            'Lines',
            'CustomerName',
            'ShipmentNbr',
            'Total_WarrantyRevenue',
            'Date_Month',
            'Date_Year',
            'FinPeriod',
            'LastChecked',
        ],
    },
    'acu.InventorySummary': {
        'keys': [
            'InventoryCD',
        ],
        'columns': [
            'InventoryCD',
            'Description',
            'Depth',
            'Length',
            'Width',
            'Volume',
            'Weight',
            'Price',
            'Cost',
            'oldSKU',
            'VendorID',
            'ItemType',
            'ItemClass',
            'PostingClass',
            'TaxCategory',
            'DefaultWH',
            'ReplenishmentClass',
            'RC_Min',
            'RC_Max',
            'VendorPartNumber',
            'UPC',
            'InsertedDT',
            'LastModifiedDT',
            'ItemClassDesc',
            'EDPNO',
            'LastChecked',
        ],
        'update_columns': [
            'Description',
            'Depth',
            'Length',
            'Width',
            'Volume',
            'Weight',
            'Price',
            'Cost',
            'oldSKU',
            'VendorID',
            'ItemType',
            'ItemClass',
            'PostingClass',
            'TaxCategory',
            'DefaultWH',
            'ReplenishmentClass',
            'RC_Min',
            'RC_Max',
            'VendorPartNumber',
            'UPC',
            'LastModifiedDT',
            'ItemClassDesc',
            'EDPNO',
            'LastChecked',
        ],
    },
    'analytics.JHL_B2BCollectionsDetail': {
        'keys': [
            'CustomerID',
            'RefNbr',
        ],
        'columns': [
            'CustomerID',
            'CustomerName',
            'RefNbr',
            'OrigRefNbr',
            'DocDate',
            'DueDate',
            'DocStatus',
            'DaysOverdue',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'SalespersonID',
            'TermsID',
            'CustomerStatus',
            'State',
            'Phone',
            'Email',
            'SendStatementByEmail',
            'InvoicePhone1',
            'InvoiceEmail',
            'Phone1',
            'Phone2',
            'Phone3',
            'InvoicePhone_Coalesce',
            'InvoicePhone2',
            'InvoicePhone3',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'CustomerName',
            'OrigRefNbr',
            'DocDate',
            'DueDate',
            'DocStatus',
            'DaysOverdue',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'SalespersonID',
            'TermsID',
            'CustomerStatus',
            'State',
            'Phone',
            'Email',
            'SendStatementByEmail',
            'InvoicePhone1',
            'InvoiceEmail',
            'Phone1',
            'Phone2',
            'Phone3',
            'InvoicePhone_Coalesce',
            'InvoicePhone2',
            'InvoicePhone3',
            'LastChecked',
        ],
    },
    'analytics.JHL_B2BCollectionsSummary': {
        'keys': [
            'CustomerID',
        ],
        'columns': [
            'CustomerID',
            'CustomerName',
            'SalespersonID',
            'TermsID',
            'CustomerStatus',
            'State',
            'Email',
            'Phone',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'CustomerName',
            'SalespersonID',
            'TermsID',
            'CustomerStatus',
            'State',
            'Email',
            'Phone',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'LastChecked',
        ],
    },
    'analytics.JHL_B2BCollectionsSummary_Snapshot': {
        'keys': [
            'CustomerID',
            'Timestamp',
        ],
        'columns': [
            'CustomerID',
            'CustomerName',
            'SalespersonID',
            'TermsID',
            'CustomerStatus',
            'State',
            'Email',
            'Phone',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'Timestamp',
        ],
        'update_columns': [
            'CustomerName',
            'SalespersonID',
            'TermsID',
            'CustomerStatus',
            'State',
            'Email',
            'Phone',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
        ],
    },
    'analytics.JHL_B2BCollectionsByStatus': {
        'keys': [
            'CustomerStatus',
        ],
        'columns': [
            'CustomerStatus',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'LastChecked',
        ],
    },
    'analytics.JHL_B2BCollectionsByStatus_Snapshot': {
        'keys': [
            'CustomerStatus',
            'Timestamp',
        ],
        'columns': [
            'CustomerStatus',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'Timestamp',
        ],
        'update_columns': [
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
        ],
    },
    'analytics.JHL_B2BCollectionsBySalesRep': {
        'keys': [
            'SalespersonID',
        ],
        'columns': [
            'SalespersonID',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'InsertedDT',
            'LastChecked',
        ],
        'update_columns': [
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'LastChecked',
        ],
    },
    'analytics.JHL_B2BCollectionsBySalesRep_Snapshot': {
        'keys': [
            'SalespersonID',
            'Timestamp',
        ],
        'columns': [
            'SalespersonID',
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
            'Timestamp',
        ],
        'update_columns': [
            'CurrentBalance',
            'Balance_1_30d',
            'Balance_31_60d',
            'Balance_61_90d',
            'Balance_90d',
            'TotalBalance',
        ],
    },
    'SOOrderKvExt': {
        'keys': [
            'CompanyID',
            'RecordID',
            'FieldName',
        ],
        'columns': [
            'CompanyID',
            'RecordID',
            'FieldName',
            'ValueNumeric',
            'ValueDate',
            'ValueString',
            'ValueText',
        ],
        'update_columns': [
            'ValueNumeric',
            'ValueDate',
            'ValueString',
            'ValueText',
        ],
    },
    
    
    
    
}

'''# Tables

Tables is used to drive the SQLConnector's checked_upsert functionality

<hr>

## Structure
 >>> 'table_name': { #replace table_name with the name of the table. We'll use AdDetails
        'keys': [ #replace keys entries with the names of the primary key column(s) in the table
            'primary_key_column_1', 
            'primary_key_column_2'
        ],
        'columns': [ #replace column entries with the names of all columns in the table
            'primary_key_column_1',
            'primary_key_column_2',
            'column_1',
            'column_2',
            'column_3'
        ],
        'update_columns': [ #replace update_columns entries with column names that are NOT keys
            'column_1',
            'column_2',
            'column_3'
        ],
 }
 
 >>> 'AdDetails': {
        'keys': [
            'AdCode',
        ],
        'columns': [
            'AdCode',
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
        'update_columns': [
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
 }
'''



# Database configurations as dictionaries
DATABASES = {
    'db_CentralStore': {
        'server': os.getenv('CENTRALSTORE_SERVER'),
        'database': os.getenv('CENTRALSTORE_DATABASE'),
        'username': os.getenv('CENTRALSTORE_USERNAME'),
        'password': os.getenv('CENTRALSTORE_PASSWORD'),
    },
    'AcumaticaDb': {
        'server': os.getenv('ACUMATICA_SERVER'),
        'database': os.getenv('ACUMATICA_DATABASE'),
        'username': os.getenv('ACUMATICA_USERNAME'),
        'password': os.getenv('ACUMATICA_PASSWORD'),
    },
    'AcudevDb': {
        'server': os.getenv('ACUDEV_SERVER'),
        'database': os.getenv('ACUDEV_DATABASE'),
        'username': os.getenv('ACUDEV_USERNAME'),
        'password': os.getenv('ACUDEV_PASSWORD'),
    }
}

AVS = {
    'account': os.getenv('AVS_ACCOUNT'),
    'license': os.getenv('AVS_LICENSE')
}
RMI = {
    'username': os.getenv('RMI_USERNAME'),
    'password': os.getenv('RMI_PASSWORD')
}

REDSTAG = {
    'username': os.getenv('REDSTAG_USERNAME'),
    'password': os.getenv('REDSTAG_PASSWORD')
}

ACUMATICA_API = {
    'username': os.getenv('ACUMATICA_API_USERNAME'),
    'password': os.getenv('ACUMATICA_API_PASSWORD'),
    'username2': os.getenv('ACUMATICA_API_USERNAME2'),
    'password2': os.getenv('ACUMATICA_API_PASSWORD2'),
    'username3': os.getenv('ACUMATICA_API_USERNAME3'),
    'password3': os.getenv('ACUMATICA_API_PASSWORD3'),
    'username4': os.getenv('ACUMATICA_API_USERNAME4'),
    'password4': os.getenv('ACUMATICA_API_PASSWORD4'),
    'username5': os.getenv('ACUMATICA_API_USERNAME5'),
    'password5': os.getenv('ACUMATICA_API_PASSWORD5'),
    'username6': os.getenv('ACUMATICA_API_USERNAME6'),
    'password6': os.getenv('ACUMATICA_API_PASSWORD6'),
    'cf_client_id': os.getenv('CF_ACCESS_CLIENT_ID'),
    'cf_client_secret': os.getenv('CF_ACCESS_CLIENT_SECRET'),
}

CRITEO = {
    'client_id': os.getenv('CRITEO_CLIENT_ID'),
    'client_secret': os.getenv('CRITEO_CLIENT_SECRET'),
    'ad_id': os.getenv('CRITEO_ADVERTISER_ID')
}

KUSTOMER = {
    'webhook': os.getenv('KUSTOMER_WEBHOOK')
}

HUBSPOT = {
    'access_token': os.getenv('HUBSPOT_ACCESS_TOKEN')
}

SHOPIFY = {
    'domain': 'journey-health-lifestyle.myshopify.com',
    'version': "2024-07",
    'token': os.getenv('SHOP_API_TOKEN'),
    'key': os.getenv('SHOP_API_KEY'),
    'secret': os.getenv('SHOP_API_SECRET')
}

TEAMS = {
    'tenant_id':        os.getenv('TEAMS_TENANT_ID'),
    'client_id':        os.getenv('TEAMS_CLIENT_ID'),
    'client_secret':    os.getenv('TEAMS_CLIENT_SECRET'),
    'user_id':          os.getenv('TEAMS_USER_ID'),
    'sp_object_id':     os.getenv('TEAMS_SP_OBJECT_ID'),
    'webhook_url':      os.getenv('TEAMS_WEBHOOK_URL'),
}


AFTERSHIP = {
    'api_key': os.getenv('AFTERSHI_API_KEY')
}


SHAREPOINT = {
    'directory_id': os.getenv('SHAREPOINT_DIRECTORY_ID'),
    'client_secret_id': os.getenv('SHAREPOINT_CLIENT_SECRET_ID'),
    'client_secret_value': os.getenv('SHAREPOINT_CLIENT_SECRET_VALUE'),
    'object_id': os.getenv('SHAREPOINT_OBJECT_ID'),
    'app_id': os.getenv('SHAREPOINT_APP_ID'),
}


JHL_SFTP: dict = {
    'host': os.getenv('SFTP_JHL_HOST'),
    'port': os.getenv('SFTP_JHL_PORT'),
    'username': os.getenv('SFTP_JHL_USERNAME'),
    'password': os.getenv('SFTP_JHL_PASSWORD'),
}

DARWILL_SFTP: dict = {
    'host': os.getenv('SFTP_DARWILL_HOST'),
    'port': os.getenv('SFTP_DARWILL_PORT'),
    'username': os.getenv('SFTP_DARWILL_USERNAME'),
    'password': os.getenv('SFTP_DARWILL_PASSWORD'),
}