create view klaviyo.Profile_AllDetails
as
select h.ID
	 , h.PhoneNumber FmtPhoneNumber
	 , h.Email
	 , h.FirstName
	 , h.LastName
	 , h.Name
	 , h.Organization
	 , h.Locale
	 , h.RawPhoneNumber
	 , h.Title
	 , h.ExternalID
	 , h.Created
	 , h.Updated
	 , h.JoinedGroupAt
	 , p.AcceptsMarketing
	 , p.ShopifyTags
	 , p.DateCreated
	 , p.LastMailedDate
	 , p.LastOpenedDate
	 , p.Consent
	 , p.ConsentTimestamp
	 , p.Source
	 , p.PhoneNumberRegion
	 , p.HubspotRecordID
	 , p.LeadStatusPhone
	 , p.ContactOwnerPhone
	 , p.Timestamp
	 , p.CreativeID
	 , p.SMSAttentiveSignup
	 , p.SMSConsentMethod
	 , p.ConsentMethod
	 , p.ConsentFormID
	 , p.ConsentFormVersion
	 , p.ExpectedDateOfNextOrder
	 , p.UTMSource
	 , p.UTMMedium
	 , p.UTMCampaign
	 , p.ShoppingFor
	 , p.MobilityIssues
	 , p.Features
	 , p.Brand
	 , p.VeteranStatus
	 , p.Birthday
	 , p.Clicks
	 , p.Opens
	 , p.FullName
	 , p.CustomerID
	 , p.MothersDayOptOut
	 , p.NumberOfOrders
	 , p.Latitude
	 , p.Longitude
	 , p.InitialSource
	 , p.LastSource
	 , p.StoreInterest
	 , p.Coupon
	 , p.OkendoFamilyName
	 , p.OkendoGivenName
	 , p.Product
	 , p.UTMContent
	 , p.UtmTerm
	 , p.Company
	 , p.HubspotOriginalSource
	 , p.HubspotOriginalSourceDrillDown1
	 , p.HubspotOriginalSourceDrillDown2
	 , p.ProductForYouOrSomeoneElse
	 , p.PrimaryProductUser
	 , p.TypeOfFirstEngagement
	 , p.LeadSource
	 , p.BreadFinanceOutcome
	 , p.ShippingState
	 , p.ShippingZip
	 , p.TextOptIn
	 , p.EmailOption
	 , p.MemberHasAccessedPrivateContent
	 , p.LegalBasis
	 , p.OkendoNumberOfSurveyResponses
	 , p.AmazonInterest
	 , p.LastReferringDomain
	 , p.InterestedInCategory
	 , p.HasReceivedDigitalCatalog
	 , p.AmazonOrStore
	 , p.FathersDayOptOut
	 , p.InitialReferringDomain
	 , p.LastContactedOnPhone
	 , p.LastEventDate
	 , p.OkendoAverageReviewRating
	 , p.OkendoHasSubmittedMedia
	 , p.OkendoLatestReviewRating
	 , p.OkendoNumberOfReviews
	 , p.OkendoAverageReviewSentiment
	 , p.OkendoLatestReviewSentiment
	 , p.UserStatus
	 , p.AdditionalEmail
	 , p.CallDisposition
	 , p.DateOrderPlaced
	 , p.RepEmail
	 , p.Unengaged
	 , p.OkendoLatestNPSCategory
	 , p.OkendoLatestNPS
	 , p.OkendoLatestNPSDate
	 , p.TypeOfFirstEngagementHubspot
	 , p.ItemDescription
	 , p.Undefined
	 , p.UgcFreeItem
	 , p.CompanyID
	 , p.EmailContentPreference
	 , s.Mkt_Email_CanReceiveEmail
	 , s.Mkt_Email_Consent
	 , s.Mkt_Email_ConsentTimestamp
	 , s.Mkt_Email_LastUpdated
	 , s.Mkt_Email_Method
	 , s.Mkt_Email_MethodDetail
	 , s.Mkt_Email_CustomMethodDetail
	 , s.Mkt_Email_DoubleOptin
	 , s.OpenTrk_Email_Consent
	 , s.OpenTrk_Email_ConsentTimestamp
	 , s.OpenTrk_Email_LastUpdated
	 , s.OpenTrk_Email_CreatedTimestamp
	 , s.OpenTrk_Email_Metadata
	 , s.OpenTrk_Email_CanReceive
	 , s.OpenTrk_Email_ValidUntil
	 , s.ClickTrk_Email_Consent
	 , s.ClickTrk_Email_ConsentTimestamp
	 , s.ClickTrk_Email_LastUpdated
	 , s.ClickTrk_Email_CreatedTimestamp
	 , s.ClickTrk_Email_Metadata
	 , s.ClickTrk_Email_CanReceive
	 , s.ClickTrk_Email_ValidUntil
	 , s.Mkt_SMS_CanReceiveSMS
	 , s.Mkt_SMS_Consent
	 , s.Mkt_SMS_ConsentTimestamp
	 , s.Mkt_SMS_Method
	 , s.Mkt_SMS_MethodDetail
	 , s.Mkt_SMS_LastUpdated
	 , s.Txn_SMS_CanReceiveSMS
	 , s.Txn_SMS_Consent
	 , s.Txn_SMS_ConsentTimestamp
	 , s.Txn_SMS_Method
	 , s.Txn_SMS_MethodDetail
	 , s.Txn_SMS_LastUpdated
	 , s.Mkt_Push_CanReceivePush
	 , s.Mkt_Push_Consent
	 , s.Mkt_Push_ConsentTimestamp
	 , h.InsertedDT
	 , h.LastChecked
from klaviyo.ProfileHeader h
inner join klaviyo.ProfileProperties p on h.ID = p.ID
inner join klaviyo.ProfileSubscriptions s on h.ID = s.ID
